### ISSUE TITLE
Finalize on the baseline score

### ISSUE THREAD

**Issue by ayulockin** [cosmo3769/SSL-study#28]
We have run some experiments in the past and have achieved close to 23% top@1 accuracy but let's documents it and push the score and settle down with a baseline that we can reproduce. 

If we fail to hit 44% that's fine because the repo reporting that number didn't give reproducible code (or recipes) to achieve that.

**Comment by cosmo3769** [comment]
Moving forward with 23%. Should we close this issue or come back to it later? @ayulockin
